language: node_js
before_install:
  - "npm install npm -g"
node_js:
  - "stable"
  - "13"
  - "14"
  - "15"
script:
  - npm run test
after_success:
  - npx semantic-release
  - bash <(curl -s https://codecov.io/bash)
